### ISSUE TITLE
Should this project depend of matrix

### ISSUE THREAD

**Issue by lpatiny** [mljs/floyd-warshall#1]
@targos 

This algorithm is really based on an array of array and does not require any method from Matrix. What do you think about making or not dependent of Matrix

**Comment by targos** [comment]
I you want to support matrices that are not backed by an array of array (for example SparseMatrix, or a MatrixView), you require Matrix.
Otherwise, I think it's not a bad think to depend on Matrix. I have on my TODO list to implement a Matrix extension that allows to work with 2D or 1D arrays without copying them.
